server:
  port: 80

ingress:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-myservicea
      annotations:
        kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: aabb.com
          http:
            paths:
              - path: /
#                pathType: Exact
                backend:
                  service:
                    name: www.jtthink.com
                    port:
                      number: 80