server:
  port: 80

ingress:
  rules:
    - http:
        paths:
          - path: /
#            pathType: Exact
            backend:
              service:
                name: www.jtthink.com
                port:
                  number: 80
